message(STATUS "VCPKG_ROOT=$ENV{VCPKG_ROOT}")
if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
    message(STATUS "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}")
else()
    set(BOOST_ROOT "/mnt/d/work/egsolutions/egpstracker/eXGeo.Agent.Service/common/3rdParty/boost/boost_1_66_0/distro/linux/x86_64")
    set(OPENSSL_ROOT_DIR "/mnt/d/work/egsolutions/egpstracker/eXGeo.Agent.Service/common/3rdParty/openssl/distro/linux/x86_64")
    set(CPPREST_ROOT "/mnt/d/work/egsolutions/egpstracker/eXGeo.Agent.Service/common/3rdParty/restsdk/2.10.0/distro/linux/x86_64")
endif()